services:
  - type: web
    name: soutralideals-web
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: dist
    routes:
      # Règle indispensable pour les Single Page Applications (React Router)
      # Redirige toutes les requêtes vers index.html pour laisser le routeur gérer l'affichage
      - type: rewrite
        source: /*
        destination: /index.html
